# Generated by Django 5.2.5 on 2025-08-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.IntegerField(help_text='ID da conversa no Chatwoot para agrupar as mensagens.')),
                ('sender', models.CharField(choices=[('user', 'Usuário'), ('bot', 'Bot')], help_text='Quem enviou a mensagem.', max_length=10)),
                ('text', models.TextField(help_text='O conteúdo da mensagem.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação.')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
