# Generated by Django 5.2.5 on 2025-08-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation_id',
            field=models.IntegerField(help_text='ID da conversa para agrupar as mensagens (ex: Telegram chat_id).'),
        ),
    ]
