# Generated by Django 5.2.5 on 2025-08-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_message_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation_id',
            field=models.BigIntegerField(help_text='ID da conversa para agrupar as mensagens (ex: Telegram chat_id). Usa BigIntegerField para suportar IDs grandes do Telegram.'),
        ),
    ]
