# Generated by Django 5.2.5 on 2025-08-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_message_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('twilio_whatsapp', 'Twilio WhatsApp')], default='telegram', help_text='Canal de origem da mensagem.', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation_id',
            field=models.CharField(help_text="ID da conversa no canal de origem (ex: chat_id do Telegram, 'whatsapp:+...' do Twilio).", max_length=255),
        ),
    ]
