# Generated by Django 5.2.5 on 2025-08-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_message_channel_alter_message_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('twilio_whatsapp', 'Twilio WhatsApp'), ('chatwoot', 'Chatwoot')], help_text='Canal de origem da mensagem.', max_length=20),
        ),
    ]
